name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest  # Ahora sí corre en Windows
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Google Chrome y Chromedriver
        run: |
          choco install googlechrome -y
          choco install chromedriver -y

      - name: Configurar Chromedriver en PATH
        run: |
          echo "C:\Program Files\Google\Chrome\Application" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH
          echo "C:\ProgramData\chocolatey\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Instalar Python y dependencias
        run: |
          python -m pip install --upgrade pip
          python -m pip install selenium

      - name: Ejecutar script con Selenium
        run: python test_contacto.py

      - name: Ejecutar segundo archivo de prueba
        run: python test_reservaDatos.py
      
      - name: Ejecutar tercer archivo de prueba
        run: python check.py
