name: Run Selenium Tests

on:
  push:
    branches:
      - main  # Aquí se ejecutará el flujo cuando se haga un push en la rama main
  pull_request:
    branches:
      - main  # También puedes configurarlo para que se ejecute en pull requests

jobs:
  selenium_tests:
    runs-on: windows-latest  # Utiliza una imagen de Ubuntu para ejecutar las pruebas

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Clona el repositorio para poder acceder al código

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Especifica la versión de Python que necesitas

    - name: Install dependencies
      run: pip install selenium

    - name: Install ChromeDriver
      run: |
        sudo apt update
        sudo apt install -y chromedriver

    - name: Run Selenium tests
      run: |
        python main.py  
