name: Run Selenium Tests

on:
  push:
    branches:
      - main  # Aquí se ejecutará el flujo cuando se haga un push en la rama main
  pull_request:
    branches:
      - main  # También puedes configurarlo para que se ejecute en pull requests

jobs:
  selenium_tests:
    runs-on: ubuntu-latest  # Utiliza una imagen de Ubuntu para ejecutar las pruebas

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Clona el repositorio para poder acceder al código

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Especifica la versión de Python que necesitas

    - name: Install dependencies
      run: pip install selenium

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}" || curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium tests
      run: |
        python main.py  
